### ISSUE TITLE
Silkworm not dropping

### ISSUE THREAD

**Issue by intelic76** [fullphaser/Tame-The-World#4]
I've de-leaved a bunch of trees of varying types with the crook and I've not gotten a silkworm. Is the drop rate bugged, or is that a fake quest?

**Comment by Alnarra** [comment]
Neither the Drop Rate nor Quest is bugged so far as I'm aware. What kind of trees were you using to get the silk worms from?

**Comment by intelic76** [comment]
I was using a wooden Crook on oaks, birches (only tried a handful of these) and darkwood's so far.

**Comment by Alnarra** [comment]
I can't seem to replicate the issue, though it's worth noting that their drop rate appears to be fairly low. But I'm able to get Silkworms to drop as of 0.1.13
