### ISSUE TITLE
Big Backpack quest not working

### ISSUE THREAD

**Issue by Wolfmaster12805** [fullphaser/Tame-The-World#6]
In the backpack quest where you make a normal backpack and bound leather, then tanned leather, then the big backpack and workbench backpack, I have continuously tried to get the big backpack to work. I have tried dropping it and picking it back up, didn't work. Crafting it again, didn't work. No manual submit button that I see. If you could fix this that would be great.

**Comment by Alnarra** [comment]
This should now be corrected in the latest build
