### ISSUE TITLE
Quest book issues

### ISSUE THREAD

**Issue by Ssinssrigg** [fullphaser/Tame-The-World#8]
Thus far, completion credit for the revolver quest, and for the poppet quest and witch's brew manual don't work

**Comment by Ssinssrigg** [comment]
Same for the chalk part of the waystone quest

**Comment by Ssinssrigg** [comment]
all of your references to botania flower petals are spelled 'pedal'.

**Comment by Alnarra** [comment]
All of these save the Pedal one have been corrected, and I will get to that when I think about editing >.>
